### ISSUE TITLE
Topics from the old upstream repositories

### ISSUE THREAD

**Issue by tarsius** [emacsorphanage/org-bullets#5]
Unfortunately the original author of this package has not responded when we tried to make contact. As a result his repository could not be transferred and we had to fork instead.

Below are the topics that were open when we forked. Because we cannot close or merge these issues and pull-requests in the original repository, we instead mark them as resolved here, once that is actually the case.

### Issues

- [x] [#24 Conflicts with org-hide-emphasis-markers](https://github.com/sabof/org-bullets/issues/24)
- [x] [#23 Suggested addition to README: use-packag](https://github.com/sabof/org-bullets/issues/23)
- [x] [#22 Font Awesome Pro 5.0.](https://github.com/sabof/org-bullets/issues/22)
- [x] [#17 wierd issue in emacs 25.1](https://github.com/sabof/org-bullets/issues/17)
- [x] [#15 Transform all bullets instead of just the last one for org-indent-mode](https://github.com/sabof/org-bullets/issues/15)
- [x] [#14 Bullets for TODO](https://github.com/sabof/org-bullets/issues/14)
- [x] [#12 Incorrect third bullet poin](https://github.com/sabof/org-bullets/issues/12)
- [x] [#11 Very slow performanc](https://github.com/sabof/org-bullets/issues/11)

### Pull requests

- [x] [#21 Add several customization variables](https://github.com/sabof/org-bullets/pull/21)
- [x] [#19 Respect org-hide-leading-stars and the org-hide face](https://github.com/sabof/org-bullets/pull/19)
- [x] [#13 Add option to make the invisible leading stars.](https://github.com/sabof/org-bullets/pull/13)

**Comment by integral-dw** [comment]
Let me start with a few quick ones before working on some proper later:
#13: wontfix. Reason: Already present in [org-superstar](https://github.com/integral-dw/org-superstar-mode).
#23: wontfix. use-package, while popular, is not part of vanilla Emacs, and serves primarily as a convenience for end-users to simplify their init files.  Those who use it would already know how to integrate a simple package into their config, those who don't won't find this info helpful.
#12: seems to be correctly attributed (font issue). Since no further information has been provided, I would consider this issue resolved.

**Comment by integral-dw** [comment]
Oh right, I forgot.
#14: wontfix. Reason: Present in org-superstar (see above).

**Comment by integral-dw** [comment]
Oh, hope it's okay I checked some of the checkboxes, @tarsius . These things are so alluring it's hard to resist :sweat_smile:

**Comment by tarsius** [comment]
That was the plan. :wink:

**Comment by integral-dw** [comment]
The README as has been updated to address #11, see also https://github.com/integral-dw/org-superstar-mode/issues/3.

**Comment by integral-dw** [comment]
#19 and #21 require some compromise. Yes, ideally this package should honor `org-hide-leading-stars`.  However, if it did, I would either 
1) change the default behavior of org-bullets (forcing all current users to set the variable themselves), or
2) mess with another packages variable.

I have a fix for this in Org Superstar, but I don't want to touch Bullets to the extent necessary.
However, honoring `org-hide` (the face) is zero cost, and probably what the user expects is done.

As for the rest of the proposed changes in #21: There does not seem to be anything else that is salvageable.  The mouse event code is long gone.  What remains is a vestigial key map with no discernible use.  The documentation seems to have changed too much as well, so not much to merge there.

**Comment by integral-dw** [comment]
I am not sure I understand #15.  
> And then, when I copy and paste the block to send to someone, I get a mixture of regular (`*`) stars and UTF-8 stars in the headlines.

The package does not change the buffer's contents, so the pasted content should not have any UTF-8 characters in the first place.  If it's about "seeing" the asterisks when you mark a region, this can be mitigated by setting up org-hide (there are other tricks to do this, but those are out of the question because they would change too much code).  So I guess it's a wontfix.

**Comment by integral-dw** [comment]
I fail to reproduce #24 with `emacs -Q`.  Given the Issue is from 2018, whatever caused the bug is either fixed now or it depends on missing information.

**Comment by integral-dw** [comment]
I also fail to reproduce #17 (Emacs 26.3).  This class of issues may relate to the font strangeness of Emacs 25.3 [uncovered here](https://github.com/integral-dw/org-superstar-mode/issues/8).  It is likely dependant on the OS's font config.  Sadly there is not much I can do about it without more information. :(

**Comment by tarsius** [comment]
> Sadly there is not much I can do about it without more information.

IMO it is perfectly okay to consider such issues resolved here but you should probably comment on the original issue and state that the original poster has to provide more information if they are still experiencing the issue.

**Comment by integral-dw** [comment]
I was considering that, will do!

**Comment by integral-dw** [comment]
Done. I think that should take care of all issues for now.  I have linked most issues to the repo itself instead of here, because I think it's best for them to open new issues should anything act up.

**Comment by tarsius** [comment]
That makes sense and because I've listed all the issue urls above there's already a backlink anyway.
